### ISSUE TITLE
[Feature request] 세이버팀입니다.

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slaps-saver#110]
##  몇개 기사 테스트한 의견 전달드립니다. 
1.	헤드라인 글자수 제한 삭제 : 글자제한 없이 입력 가능하도록 부탁드립니다.

~~2.	본문  단락 : 아래와 같은 기능이 가능했으면 합니다.~~
        1) 들여쓰기
	2) 줄변경
	3) 링크 기능
	4) 사진 첨부
	
~~3.	카테고리 : 정치/ 경제/사회/ 국제/ 문화로 5 가지로 반영 부탁드립니다.~~

감사합니다.

#112 #113

**Comment by kenu** [comment]
2., 3. 이슈 분리

**Comment by kenu** [comment]
`4) 사진 첨부` 이슈 분리
#124
