### ISSUE TITLE
[Refactoring] 회원가입 전체로직 수정

### ISSUE THREAD

**Issue by earthkingman** [innovationacademy-kr/slaps-saver#117]
### 내용
로직 및 구조 리팩토링
#### authorController.js 
- presignup
  - [x] redirect 형식에서 json 형식으로 변환
- decision
  - [x] redirect 형식에서 json 형식으로 변환
  - [x] alert 함수삭제 
- inviteRequest 
  - [x] 빈 항목검사 부분 리팩토링
- signup
  - [x] 비밀번호와 확인비밀번호 부분 리팩토링
### View
- author/signup.ejs
  - [x] form -> axios

### Model
- Invitation 테이블
   - [x] code컬럼이 중복적인 기능을 함  -> category, position 나누기

**Comment by earthkingman** [comment]
- presignup 9bf1d25c0924698ea5ac30b17a12330cf37d5e3b

**Comment by padawanR0k** [comment]
- signup.js, invitaion 테이블, signup.ejs 09f89b4013763671ba7c6ffc5127ad7711d11d91
