### ISSUE TITLE
[세이버팀] ' 더 자세히' 버튼 관련

### ISSUE THREAD

**Issue by Jung-Saver** [innovationacademy-kr/slaps-saver#154]
메인 페이지에서 '더 자세히' 버튼은 누르면,

뎁스를 들어가서 페이지 확장되는 것이 아니고,

메인페이지 내에서 페이지가 확장되어야 합니다.

확인 부탁드려요

**Comment by padawanR0k** [comment]
@Jung-Saver 

전달해주신 시안을 기준으로 보았을 때 [메인페이지, 상세화면]이 존재합니다. 두개의 시안은 상단 영역이 다르며, 메인페이지에서는 [더 자세히보기 +]만 있고, 접는 버튼의 UI는 없습니다. 
또한 메인페이지에서 '더 자세히' 버튼을 누르지 않았을 때 소단락이 몇번째까지 보여지는지에 대한 기준이 없었습니다.  이를 바탕으로 현재는 상세페이지 형태로 개발하였습니다

추가로, 만약 상세페이지가 없이 화면확장으로 개발될 경우
1. 북마크화면에서 내가 북마크한 기사 클릭시 이동할 화면
2. 기사를 공유했을때 공유한 링크를 클릭하고 들어왔을때 보이는 화면

이 두가지가 애매해질거같습니다.
이에 대해 추가적인 피드백을 해주시면 좋을거같습니다.

**Comment by Jung-Saver** [comment]
이유록님
 
안녕하세요? 세이버팀 김정선입니다.
 
문의주신 사항에 대해서 다음과 같이 답변 드립니다. 
 
1) 세이버는 악시오스와 같이 초기메인화면에서 이동을 최소화하는 기획입니다.
  수정요청 드린 것처럼, 메인화면에서 '더 자세히'버튼을 누르면 기사 페이지가 확장되어 보이도록 
  기획되었습니다. 악시오스 페이지를 참조하시면 알 수 있습니다. 
 
2) '접기'버튼은 UI 없는 것이 맞습니다. 접기 기능을 기획하지 않았습니다.
 
3)  상세페이지느 개발 되는 것이 맞습니다. 입력된 기사는 초기화면과 상세페이지 (저장이나 공유 시 보이는 )에
   노출되는 방식입니다. 
 
4) 메인화면 노출
  - CMS 기획서에 보시면 확장전 화면에선 기본적으로 100자 내외 브리핑까지 노출됩니다. 콘텐츠에 따라 추가
   콘텐츠가 노출될 필요가 있을 것으로 예상되어, 첫번째 소단락까지 노출이 가능하도록 버튼 개발을 요청드렸습니다. 
  
내용확인하실 수 있는 기획서 페이지를 전달드립니다. 
 
더 궁금하신 사항이 있으시면 편하게 말씀 주세요
 
감사합니다.
 
김정선 드림


tx_cinelux님의블로그
자기소개가없습니다.

 
-----Original Message-----

**Comment by Yenowme** [comment]
안녕하세요 
카뎃 정예나입니다! 상세한 피드백 감사합니다. 

하나 더 여쭤볼 게 있는데,
오늘의 한마디 메인노출이 언제, 어떻게 이루어지는지
( 예를들면 노출할 날짜를 예약해서 지정할지, 그때그때 편집장이 게제 버튼을 눌러 오늘의 한마디를 정할건지)
상세한 시나리오나 타임테이블이 있어야 개발이 더 진행될 듯 합니다. 
답변 부탁드리겠습니다.
우선순위가 아니라면 다른 것 먼저 진행하겠습니다. 

감사합니다.

**Comment by padawanR0k** [comment]
@Jung-Saver 
답변감사합니다. 😄  
그런데 기획서 페이지 전달이 누락된거같습니다

**Comment by Jung-Saver** [comment]
정예나님
 
안녕하세요? 문의주신 사항에 답변 드립니다. 
 
지난 번에 말씀 나눈 거처럼 이건으로 기준시간과 로직을 정리해야 작업이 가능한 사항이라,
다른 사항을 먼저 진행해주셨으면 합니다,
 
감사합니다.
 
김정선 드림
 


tx_cinelux님의블로그
자기소개가없습니다.

 
-----Original Message-----

**Comment by Jung-Saver** [comment]
유록님
 
제가 메일로 회신하면서 첨부해드렸는데, 가지 않은 모양입니다.
 
메일주소 알려주시면 보내드리겠습니다.
 
감사합니다.
 
김정선 드림


tx_cinelux님의블로그
자기소개가없습니다.

 
-----Original Message-----

**Comment by padawanR0k** [comment]
@Jung-Saver padawanr0k@gmail.com 로 전달해주시면 감사하겠습니다

**Comment by padawanR0k** [comment]
업데이트되었습니다 #165
