### ISSUE TITLE
[Bug report] 작성 기사 출고 및 게재 오류 

### ISSUE THREAD

**Issue by kenu** [innovationacademy-kr/slaps-saver#155]
## 발생 일시
#153 

## 증상
 1) 작성기사 -  편집관리 초기 화면에 기사 등록이 안됨 
 2) 초기화면 등록된 기사 - 출고 및 게재 업데이트가 안되고, invalid date로 뜸

**Comment by padawanR0k** [comment]
### 원인
- 테이블과 카테고리 상수를 변경했으나 기존 seeder그대로 사용함으로 발생
