### ISSUE TITLE
[Bug report] 특정 상황 기사 생성불가

### ISSUE THREAD

**Issue by padawanR0k** [innovationacademy-kr/slaps-saver#174]
## 발생 위치
- 기사 작성페이지
## 증상
- 기사 작성 실패가 뜸

**Comment by Jung-Saver** [comment]
기사 입력 후 임시저장까지 문제없이 진행.
이후 '내 기사 목록'에서 해당 기사를 불러오면 소단락 내용이 없는 오류가 발생합니다
