### ISSUE TITLE
[Invalid] 기사의 상태라는게 Boolean 값으로 처리가 될 수 있나?

### ISSUE THREAD

**Issue by simian114** [innovationacademy-kr/slaps-saver#37]
## 내용
기존에는 기사의 상태를 `Boolean` 으로 만들고 임시저장이면 false, 완료면 true 값으로 처리하게 만들었습니다.
하지만 기사의 상태는 아래처럼 5가지가 되어야하는게 아닌가 싶습니다.
1. 임시저장
2. 완료
3. 데스크의 승인
4. 편집장의 승인
5. 출고됨

**Comment by kmin-283** [comment]
기자의 `내 기사목록` 시나리오 상에서
```
헤드라인 (15자)/ 입력일시 / 출고여부: O 또는 X / 사진 업로드 여부: O 또는 X / 상태:
임시저장 또는 완료로 정보가 표시된다.
```
위와같이 표현되어있었기 때문에 2가지 상태만 생각했었습니다.

데스크의 승인, 편집장의 승인, 출고됨 상황은 내 기사목록 화면이 아닌 `로그인 후 보이는 메인화면`에서 보여야 되는 것인데
이 내용을 통합하여 상태를 5개로 분류하는 것도 좋다고 생각합니다!

그리고 만약 통합을 한다면 따로 현재 메인화면 및 내 기사목록에서 보이는 출고, 승인란을 제거하고,
상태란에서 모두 처리하는 것이 더 낫다고 생각합니다.

**Comment by simian114** [comment]
의견 공유 감사합니다. 말씀하신 해주신 것처럼 하나의 상태로 관리하게 된다면 굳이 `출고`, `승인` 란이 있을 필요 없이 `상태` 하나로 관리할 수 있게 되겠네요.

새로운 리팩토링 이슈를 하나 만들어서 추후 수정하도록 하겠습니다.
