### ISSUE TITLE
[Refactoring] 이미지 저장 폴더 변경하기

### ISSUE THREAD

**Issue by simian114** [innovationacademy-kr/slaps-saver#45]
## 내용
현재 모든 이미지를 `public/images/articleImages/` 에 저장하는 중.
년 / 월 폴더를 만들고 이미지를 기사 작성날짜를 기준으로  해당하는 폴더에 넣도록 수정한다.

해당 변화로 현재 이미지를 찾아서 유저에게 보여지는 방식을 수정해야한다. 어떻게? 이미지 경로를 모델에 저장하거나 또는 해당 기사의 createAt 을 기준으로 찾아가자

**Comment by kenu** [comment]
2차로 이관
