### ISSUE TITLE
[Invalid] author라는 라우터의 이름이 적합한가?

### ISSUE THREAD

**Issue by kmin-283** [innovationacademy-kr/slaps-saver#46]
## 내용
현재까지 author라는 라우터를 활용하고 있습니다.

admin은 로그인 이후 passport로 생성된 req.user.code를 활용하기 위해서 author라우터에 있어야 합니다.

그런데 admin은 author가 아닌 사람입니다....

그래서 author 라우터의 이름을 press 정도로 변경하는 것이 어떨까 생각합니다

**Comment by kenu** [comment]
user 와 구분 필요
