### ISSUE TITLE
[Feature request] 기사상세 접속시 타이틀 변경

### ISSUE THREAD

**Issue by kenu** [innovationacademy-kr/slaps-saver#92]
## 내용
기사 상세로 들어갔을 경우 Title이 변경될 필요가 있습니다.
일반페이지: `SAVER`
상세페이지: `politic article - SAVER` 처럼 보이면 좋을 것 같습니다.

<img width="473" alt="스크린샷 2021-05-26 오후 3 22 42" src="https://user-images.githubusercontent.com/718691/119611998-547e3200-be36-11eb-94dc-22dad2d2afc2.png">

**Comment by simian114** [comment]
확인이 늦었습니다! 타이틀까지는 신경을 쓰지 못했네요. 내일 회의 이후에 바로 반영하겠습니다.
